spring:
  profiles:
    active: local
  application:
    name: shop
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:frankitShop
    username: sa
    password: ''

server:
  port: 8080
  servlet:
    context-path: /api

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql  # data.sql 파일이 실행될 수 있음

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true         # 쿼리 로그 포맷 (정렬)
        #show_sql: true           # 쿼리 로그 출력
    defer-datasource-initialization: true # hibernate가 초기화 후 스키마 생성, 데이터 생성

  output:
    ansi:
      enabled: ALWAYS

  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: "localhost"
    port: 6379
    password:

---
spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true         # 쿼리 로그 포맷 (정렬)
        #show_sql: true
  redis:
    host: "127.0.0.1"
    port: 6379
    password: