spring:
  profiles:
    active: local
  application:
    name: shop
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:frankitShop
    username: sa
    password: ''

server:
  port: 8080
  servlet:
    context-path: /api

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true         # 쿼리 로그 포맷 (정렬)
        #show_sql: true           # 쿼리 로그 출력

  output:
    ansi:
      enabled: ALWAYS

  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: "localhost"
    port: 6379
    password:

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true         # 쿼리 로그 포맷 (정렬)
        #show_sql: true
  redis:
    host: "localhost"
    port: 6379
    password: 6024