INSERT INTO users (id, email, password, name, role) VALUES (1, 'admintest123@naver.com', '$2a$10$NzatKRqe3sNsO4/b2TWBOemzvu9I0jSbmiQANxlBiYkUCV7ZpFGU.', '테스터어드민', 'ADMIN');
INSERT INTO users (id, email, password, name, role) VALUES (2, 'usertest123@naver.com', '$2a$10$NzatKRqe3sNsO4/b2TWBOemzvu9I0jSbmiQANxlBiYkUCV7ZpFGU.', '테스터유저', 'USER');

INSERT INTO product (name, description, price, delivery_fee) VALUES ('컴퓨터1', '컴퓨터입니다', '1100000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('컴퓨터2', '컴퓨터입니다', '1200000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('컴퓨터3', '컴퓨터입니다', '1300000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('컴퓨터4', '컴퓨터입니다', '1500000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('컴퓨터5', '컴퓨터입니다', '2100000', '7000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('휴대폰1', '휴대폰입니다', '1000000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('휴대폰2', '휴대폰입니다', '1200000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('휴대폰3', '휴대폰입니다', '1250000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('휴대폰4', '휴대폰입니다', '1320000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('휴대폰5', '휴대폰입니다', '990000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('유니폼1', '유니폼입니다', '100000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('유니폼2', '유니폼입니다', '115000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('유니폼3', '유니폼입니다', '110000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('유니폼4', '유니폼입니다', '110000', '5000');
INSERT INTO product (name, description, price, delivery_fee) VALUES ('유니폼5', '유니폼입니다', '110000', '5000');

INSERT INTO product_option (product_id, name, type, extra_price) VALUES (1, 'FREE', 'S', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (2, 'FREE', 'S', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (3, 'FREE', 'S', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (4, 'FREE', 'S', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (5, 'FREE', 'S', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (6, 'FREE', 'S', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (7, 'FREE', 'S', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (8, 'FREE', 'S', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (9, 'FREE', 'S', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (10, 'FREE', 'S', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (11, '스몰', 'I', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (11, '미디움', 'I', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (11, '라지', 'I', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (12, '스몰', 'I', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (12, '미디움', 'I', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (12, '라지', 'I', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (13, '스몰', 'I', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (13, '미디움', 'I', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (13, '라지', 'I', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (14, 'FREE', 'S', 0);
INSERT INTO product_option (product_id, name, type, extra_price) VALUES (15, 'FREE', 'S', 0);
